### ISSUE TITLE
Missing context on logout

### ISSUE THREAD

**Issue by rconnett** [doordeck/doordeck-sdk-flutter#9]
Hi @RafaRuiz 

After upgrading to the latest version 2.0.5 I'm getting this error 

`.pub-cache/hosted/pub.dartlang.org/doordeck_flutter_plugin-2.0.5/android/src/main/kotlin/com/doordeck_flutter_plugin/DoordeckFlutterPlugin.kt: (58, 33): No value passed for parameter 'context'`

It looks like the logout method needs to have the context passed to it.

**Comment by RafaRuiz** [comment]
hey @rconnett 
it's been fixed now, and you have version 2.0.6 available from pub.dev.
Thanks for the report.
